name: Distribute iOS App

on:
  pull_request:
    branches:
      - release
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest

    steps: 
      - uses: actions/checkout@v4
      
      # SSH key 설정 (Match 레포지토리와의 연결)
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.3'
      
      - name: Install dependencies
        run: bundle install

      # PR 브랜치에 따라 다른 Fastlane 실행
      - name: Run Fastlane
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "release" ]]; then
            bundle exec fastlane release --verbose
          elif [[ "${{ github.event.pull_request.base.ref }}" == "develop" ]]; then
            bundle exec fastlane beta --verbose
          fi
        env: 
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
